using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace SynSpellTomeNameExtender
{
    public class Program
    {
        private static Lazy<Settings> _Settings = null!;
        public static Settings Settings => _Settings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _Settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "SynSpellTomeNameExtender.esp")
                .Run(args);
        }
        public static IPatcherState<ISkyrimMod, ISkyrimModGetter> State;
        public static Dictionary<FormKey, string> Dict = new Dictionary<FormKey, string>();

        public static HashSet<string> IgnoredPlugins = new(StringComparer.OrdinalIgnoreCase)
        {
            "EldenSkyrim_RimSkills.esp",
            "EldenSkyrim.esp",
            "EldenPerkTree.esp"
        };

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            State = state;
            SpellTypeDictory();
            
            foreach (var key in Settings.IgnoredMods)
            {
                IgnoredPlugins.Add(key.ToString());
            }

            foreach (var book in state.LoadOrder.PriorityOrder.Book().WinningOverrides())
            {
                switch (book.Teaches)
                {
                    case IBookSpellGetter teachesSpell:
                        if (IgnoredPlugins.Contains(teachesSpell.Spell.FormKey.ModKey.ToString())) continue;

                        Book updatedBook = state.PatchMod.Books.GetOrAddAsOverride(book);
                        updatedBook.Name = UpdateName(teachesSpell, updatedBook.Name);
                        //state.PatchMod.Books.GetOrAddAsOverride(updatedBook);
                        break;
                    default:
                        break;
                }
            }
        }

        public static string UpdateName(IBookSpellGetter teachesSpell, string currentName)
        {
            string nameAddition;
            if (teachesSpell.Spell.TryResolve(State.LinkCache, out var spell))
            {
                if (Dict.TryGetValue(spell.HalfCostPerk.FormKey, out nameAddition)) { }
                else nameAddition = "";
            }
            else return currentName;

            currentName = currentName.Replace("Spell Tome", "Spell Tome" + nameAddition);

            return currentName;
        }

        public static void SpellTypeDictory()
        {
            Dict.Add(FormKey.Factory("0F2CA8:Skyrim.esm"), " " + Settings.Destruction_Novice);
            Dict.Add(FormKey.Factory("0C44BF:Skyrim.esm"), " " + Settings.Destruction_Apprentice);
            Dict.Add(FormKey.Factory("0C44C0:Skyrim.esm"), " " + Settings.Destruction_Adept);
            Dict.Add(FormKey.Factory("0C44C1:Skyrim.esm"), " " + Settings.Destruction_Expert);
            Dict.Add(FormKey.Factory("0C44C2:Skyrim.esm"), " " + Settings.Destruction_Master);

            Dict.Add(FormKey.Factory("0F2CA6:Skyrim.esm"), " " + Settings.Alteration_Novice);
            Dict.Add(FormKey.Factory("0C44B7:Skyrim.esm"), " " + Settings.Alteration_Apprentice);
            Dict.Add(FormKey.Factory("0C44B8:Skyrim.esm"), " " + Settings.Alteration_Adept);
            Dict.Add(FormKey.Factory("0C44B9:Skyrim.esm"), " " + Settings.Alteration_Expert);
            Dict.Add(FormKey.Factory("0C44BA:Skyrim.esm"), " " + Settings.Alteration_Master);

            Dict.Add(FormKey.Factory("0F2CAA:Skyrim.esm"), " " + Settings.Restoration_Novice);
            Dict.Add(FormKey.Factory("0C44C7:Skyrim.esm"), " " + Settings.Restoration_Apprentice);
            Dict.Add(FormKey.Factory("0C44C8:Skyrim.esm"), " " + Settings.Restoration_Adept);
            Dict.Add(FormKey.Factory("0C44C9:Skyrim.esm"), " " + Settings.Restoration_Expert);
            Dict.Add(FormKey.Factory("0C44CA:Skyrim.esm"), " " + Settings.Restoration_Master);

            Dict.Add(FormKey.Factory("0F2CA7:Skyrim.esm"), " " + Settings.Conjuration_Novice);
            Dict.Add(FormKey.Factory("0C44BB:Skyrim.esm"), " " + Settings.Conjuration_Apprentice);
            Dict.Add(FormKey.Factory("0C44BC:Skyrim.esm"), " " + Settings.Conjuration_Adept);
            Dict.Add(FormKey.Factory("0C44BD:Skyrim.esm"), " " + Settings.Conjuration_Expert);
            Dict.Add(FormKey.Factory("0C44BE:Skyrim.esm"), " " + Settings.Conjuration_Master);

            Dict.Add(FormKey.Factory("0F2CA9:Skyrim.esm"), " " + Settings.Illusion_Novice);
            Dict.Add(FormKey.Factory("0C44C3:Skyrim.esm"), " " + Settings.Illusion_Apprentice);
            Dict.Add(FormKey.Factory("0C44C4:Skyrim.esm"), " " + Settings.Illusion_Adept);
            Dict.Add(FormKey.Factory("0C44C5:Skyrim.esm"), " " + Settings.Illusion_Expert);
            Dict.Add(FormKey.Factory("0C44C6:Skyrim.esm"), " " + Settings.Illusion_Master);
        }

    }
}
